In [1]:
import numpy as np

def max_min_composition(R, S):
    result = np.zeros((R.shape[0], S.shape[1]))
    for i in range(R.shape[0]):
        for j in range(S.shape[1]):
            max_min = 0
            for k in range(R.shape[1]):
                max_min = max(max_min, min(R[i, k], S[k, j]))
            result[i, j] = max_min
    return result

R = np.array([[0.7, 0.6], [0.8, 0.3]])
S = np.array([[0.8, 0.1, 0.4], [0.5, 0.6, 0.7]])
result = max_min_composition(R, S)

print("Result of Max-min Composition:")
print(result)


Result of Max-min Composition:
[[0.7 0.6 0.6]
 [0.8 0.3 0.4]]


In [2]:
import numpy as np

def max_min_composition(R, S):
    result = np.zeros((R.shape[0], S.shape[1]))
    for i in range(R.shape[0]):
        for j in range(S.shape[1]):
            max_min = 0
            for k in range(R.shape[1]):
                max_min = max(max_min, min(R[i, k], S[k, j]))
            result[i, j] = max_min
    return result

# Take array values from the user
rows_R = int(input("Enter the number of rows for matrix R: "))
cols_R = int(input("Enter the number of columns for matrix R: "))
R = np.zeros((rows_R, cols_R))
for i in range(rows_R):
    for j in range(cols_R):
        R[i, j] = float(input(f"Enter the value for R[{i}][{j}]: "))

rows_S = int(input("Enter the number of rows for matrix S: "))
cols_S = int(input("Enter the number of columns for matrix S: "))
S = np.zeros((rows_S, cols_S))
for i in range(rows_S):
    for j in range(cols_S):
        S[i, j] = float(input(f"Enter the value for S[{i}][{j}]: "))

# Perform max-min composition
result = max_min_composition(R, S)

# Print the result
print("Result of Max-min Composition:")
print(result)


Result of Max-min Composition:
[[0.7 0.6 0.6]
 [0.8 0.3 0.4]]
